### PR TITLE
package sounding null-safety

### PR DESCRIPTION
**Pull request by yahu1031**
Package sounding null safety with type annotations.

### CODE REVIEW

**Comment by vytautas-pranskunas-** [comment]
Any plans to push forward?

**Comment by yahu1031** [comment]
not so sure :|

**Comment by clemeMnt** [comment]
Use this : https://github.com/JCKodel/flutter_geocoder

**Comment by AliYar-Khan** [comment]
> 
> 
> Use this : https://github.com/JCKodel/flutter_geocoder

how to use this package in project ?

**Comment by yahu1031** [comment]
> > Use this : https://github.com/JCKodel/flutter_geocoder
> 
> how to use this package in project ?

easy
```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_geocoder:
    git:
      url: https://github.com/JCKodel/flutter_geocoder.git
``` 
like this @AliYar-Khan

**Comment by ginuxone** [comment]
#68

**Comment by madatr** [comment]
..

**Comment by aloisdeniel** [comment]
I fixed it on my side!

**Pull request closed without merging**
