### PR TITLE
Migration to AndroidX, add support for language in GoogleGeocoding and fix issue with @UiThread

### PR DESCRIPTION
**Pull request by Eimji**
Hello,
I am migrating the code of my application to AndroidX, so this is a proposal for migration to AndroidX for flutter_geocoder. (https://github.com/aloisdeniel/flutter_geocoder/issues/14) I also removed buildToolsVersion, we don't need it anymore.

Edit : I also propose the following changes:
- add support for language in GoogleGeocoding
- fix issue with "Methods marked with @UiThread must be executed on the main thread" (to support the latest flutter engine version, at least the version 1.6.0 of Flutter). I mean this allows to fix the issue https://github.com/aloisdeniel/flutter_geocoder/issues/18

### CODE REVIEW

**Comment by aloisdeniel** [comment]
Thanks for your contribution !

I will review it and test it as soon as I have more free time next week !

**Comment by Eimji** [comment]
Hello

I edit my post to add new commits, thanks for your great package!

**Comment by gmcdowell** [comment]
Out of interest, would this resolve issue #21 ?

**Comment by matitalatina** [comment]
Thank @Eimji for your awesome work.
This solves the "Methods marked with @UiThread must be executed on the main thread" bug indeed.
Unfortunately, it's taking too much time to be merged.

In the meanwhile, if someone is in a hurry like me, he can change the dependencies in `pubspec.yaml` pointing to this commit.

```yaml
dependencies:
  geocoder:
    git:
      url: https://github.com/Eimji/flutter_geocoder.git
      ref: bc34cfe473bfd1934fe098bb7053248b75200241
```

**Comment by Eimji** [comment]
@gmcdowell I don't know, but I use flutter_geocoder with search_map_place.

Thanks @matitalatina You don't need to add the ref key - I also sync my fork to track updates (while waiting for the PR to be merged).

**Comment by gmcdowell** [comment]
@Eimji @matitalatina thx for your thoughts gentlemen. 

I'll have a play using the ref for time being but have to admit to being nervous about pushing this into production (key feature in my App which is used as a 'work tool' used by tens of thousands of people everyday) :|

**Comment by aloisdeniel** [comment]
Published in version `0.2.0` on pub. 

Thanks a lot for your contribution !

**Comment by mockturtl** [comment]
@aloisdeniel @Eimji Thanks!

**Pull request merged**
